# Generated by Django 4.2.27 on 2026-01-29 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('alipay', '支付宝'), ('wechat', '微信支付'), ('bank', '银行转账')], max_length=16, verbose_name='支付方式')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='支付金额')),
                ('transaction_id', models.CharField(blank=True, max_length=128, verbose_name='交易流水号')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('success', '支付成功'), ('failed', '支付失败'), ('refunded', '已退款')], default='pending', max_length=16, verbose_name='支付状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='退款时间')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '支付记录',
                'verbose_name_plural': '支付记录',
            },
        ),
    ]
